# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      
      - name: install requirements
        run: python3 -m pip install -r $GITHUB_WORKSPACE/requirements.txt
        continue-on-error: true
      
      - name: run mypy
        run: python3 -m mypy $GITHUB_WORKSPACE
        continue-on-error: true

      - name: Python Code Quality and Lint
        uses: ricardochaves/python-lint@v1.1.0
        continue-on-error: true
        with:
          # A list of all paths to test
          python-root-list: $GITHUB_WORKSPACE # optional, default is .:  
          # Use Pylint
          use-pylint: false # optional, default is true:  
          # Use pycodestyle
          use-pycodestyle: false # optional, default is true
          # Use Flake8
          use-flake8: false # optional, default is true
          # Use Black
          use-black: false # optional, default is true
          # Use mypy
          use-mypy: true # optional, default is true
          # Use isort
          use-isort: false # optional, default is true
